<?php

/**
 * @file
 * Contains ecedi_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ecedi_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ecedi_test module.
    case 'help.page.ecedi_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for test purpose only') . '</p>';
      return $output;

    default:
  }
}
